server:
  port: 8888
 
spring:
  application:    name: myvalue
  profiles:
    active: dev,prod 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NotPelos/servidoryml
          default-label: main
          search-paths:             - '*service'
        